
title: Richard Smith Webpage
description: Webpage of Dr Richard Smith.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
